name: C++ CI with Google Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake .. 
      working-directory: build

    - name: Build project
      run: make -j
      working-directory: build

    - name: Run tests
      run: ./tester
      working-directory: build
